### ISSUE TITLE
Error in Tokenizing the source code

### ISSUE THREAD

**Issue by wikazp** [hazimhanif/svd_exp1#2]
![image](https://user-images.githubusercontent.com/43385819/142788057-d39e3fa5-5e41-4a19-9e2a-7f3010ee1c7c.png)

**Comment by hazimfrodo** [comment]
Hi, have you tried checking your `x_all` value? 
`x_all` should be a sliced pandas dataframe of column 'functionSource'. 
`x_all` is not supposed to be dict object.

**Comment by wikazp** [comment]
![image](https://user-images.githubusercontent.com/43385819/143042265-36c8007b-e4c7-4dba-97cc-688b7da0648d.png)
U mean this?

**Comment by wikazp** [comment]
Added x_all = pd.DataFrame(list(demodata['functionSource']))
Got error 'int' object has no attribute 'lower'
Further proceeded with converting x_all into str, tokens generated were mere 57

![image](https://user-images.githubusercontent.com/43385819/143049042-6da2ad7d-e7a3-4314-86b6-b9e277bcf695.png)

**Comment by hazimfrodo** [comment]
The `tokenizer.fit_on_texts()` accepts a list.

So you need to pass a list of string, where each element in the list is a source code.

Okay lets see. Based on your code, try this:
```
x_all = demodata['functionSource'].tolist()
tokenizer = tf.keras.preprocessing.text.Tokenizer(char_level=False)
tokenizer.fit_on_texts(x_all)
```

It should work without error as I just tried it below:
![Screenshot from 2021-11-23 16-34-30](https://user-images.githubusercontent.com/7348874/143065249-922aa4eb-10e6-4695-8e10-c4533a59b36c.png)

**Comment by hazimfrodo** [comment]
I'm able to replicate your error
```
>>> import h5py
>>> data = h5py.File('VDISC_test.hdf5','r')
>>> mydf = pd.DataFrame(list(data['functionSource']))
>>> mydf['CWE-119']=list(data['CWE-119']); mydf['CWE-120']=list(data['CWE-120']); mydf['CWE-469']=list(data['CWE-469']); mydf['CWE-476']=list(data['CWE-476']); mydf['CWE-other']=list(data['CWE-other'])

>>>
>>> mydf.rename(columns={0:'functionSource'},inplace=True)
>>> mydf.iloc[0:5,0:]
                                      functionSource  CWE-119  CWE-120  CWE-469  CWE-476  CWE-other
0  b'default_event_handler( \n    GuiWidget *widg...    False    False    False    False      False
1  b'krb5_krbhst_init_flags(krb5_context context,...    False    False    False    False      False
2  b'swap_info_get(swp_entry_t entry)\n{\n\tstruc...    False    False    False    False      False
3  b'parseattribs4(char *&c, const Vec4 &ival = V...    False    False    False    False      False
4  b'generateExecCode(CompileState* comp)\n{\n   ...    False    False    False    False      False
>>> mydf.to_pickle("VDISC_test.pickle")
>>> x_all = mydf['functionSource']
>>> x_all
0         b'default_event_handler( \n    GuiWidget *widg...
1         b'krb5_krbhst_init_flags(krb5_context context,...
2         b'swap_info_get(swp_entry_t entry)\n{\n\tstruc...
3         b'parseattribs4(char *&c, const Vec4 &ival = V...
4         b'generateExecCode(CompileState* comp)\n{\n   ...
                                ...
127414    b'gucharmap_block_chapters_model_init (Gucharm...
127415    b'scomp(const void *v1, const void *v2)\n{\n  ...
127416    b"text_chunk_line_free(TEXT_BUFFER_REC *buffer...
127417    b"psmouse_disconnect(struct serio *serio)\n{\n...
127418    b'brasero_tool_dialog_get_burn (BraseroToolDia...
Name: functionSource, Length: 127419, dtype: object
>>> tokenizer = tf.keras.preprocessing.text.Tokenizer(char_level=False)
>>> tokenizer.fit_on_texts(list(x_all))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/vol/bitbucket/mhm1718/miniconda3/envs/pytorch1.7/lib/python3.8/site-packages/keras_preprocessing/text.py", line 222, in fit_on_texts
    seq = text_to_word_sequence(text,
  File "/vol/bitbucket/mhm1718/miniconda3/envs/pytorch1.7/lib/python3.8/site-packages/keras_preprocessing/text.py", line 60, in text_to_word_sequence
    text = text.translate(translate_map)
TypeError: a bytes-like object is required, not 'dict'
```

The problem is related to the bytes string object in the `functionSource` column.
If you see, at every entry in that column, there is a 'b' that indicates its a bytes string.
Therefore, the solution is to decode it to a literal string using `.str.decode("utf-8")`
Check the solution below:

```
>>> mydf['functionSource']=mydf['functionSource'].str.decode("utf-8")
>>> mydf['functionSource']
0         default_event_handler( \n    GuiWidget *widget...
1         krb5_krbhst_init_flags(krb5_context context,\n...
2         swap_info_get(swp_entry_t entry)\n{\n\tstruct ...
3         parseattribs4(char *&c, const Vec4 &ival = Vec...
4         generateExecCode(CompileState* comp)\n{\n    g...
                                ...
127414    gucharmap_block_chapters_model_init (Gucharmap...
127415    scomp(const void *v1, const void *v2)\n{\n    ...
127416    text_chunk_line_free(TEXT_BUFFER_REC *buffer, ...
127417    psmouse_disconnect(struct serio *serio)\n{\n\t...
127418    brasero_tool_dialog_get_burn (BraseroToolDialo...
Name: functionSource, Length: 127419, dtype: object
>>> x_all = mydf['functionSource'].tolist()
>>> tokenizer = tf.keras.preprocessing.text.Tokenizer(char_level=False)
>>> tokenizer.fit_on_texts(x_all)
>>> len(tokenizer.word_counts)
339126
>>>
```

This should solve your problem.
